# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c10d3cca4343333436d1d39f79241705e6e63ced13fdee97d360c6f0f53c3812dab62b7f8492292cbe9379d363bd52245c2cd354b6b53fae81b5364ec5917b84

test:
  secret_key_base: 8b79f68af8c38cdf21a342939c578351b09b20f2020699656e9ad3eacea81c6a893984e189fa0482eb3dfee6804b456ba378f59c0e7b31beab378091d0f7853c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
